accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserDetailView, UsersListView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('', UsersListView.as_view(), name='users'),
    path('change/', UserChangeView.as_view(), name='profile_change'),
    path('password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<slug:slug>/', UserDetailView.as_view(), name='detail_profile'),
]

hw72/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

api_urlpatterns = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include(api_urlpatterns))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path

from quotes.views import IndexView

app_name = 'quotes'

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

quotes/models.py
from django.db import models


class Quote(models.Model):
    NEW = 'new'
    MODERATED = 'mod'
    STATUS_CHOICES = [
        (NEW, 'New'),
        (MODERATED, 'Moderated'),
    ]
    text = models.TextField(max_length=666)
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=254)
    rating = models.SmallIntegerField(default=0)
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, default=NEW)
    created_at = models.DateTimeField(auto_now_add=True)

quotes/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'base.html'

quotes/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a id="quotes" class="nav-link px-2 text-white"
                       href="http://localhost:8000/api/v1/quotes/">Главная</a></li>
                <li><a id="create-quote" class="nav-link px-2 text-white"
                       href="http://localhost:8000/api/v1/quotes/">Добавить цитату</a></li>
                {% block nav %}
                {% endblock %}
            </ul>
            <div class="text-end">
                {% if user.is_authenticated %}
                    <span>Привет, <a class="px-2 text-white text-uppercase"
                                     href="{% url 'accounts:detail_profile' user.profile.slug %}">{{ user.username }}!</a></span>
                    &nbsp;
                    <a href="{% url 'accounts:logout' %}" class="btn btn-outline-light me-2">Выход</a>
                {% else %}
                    {% block login-nav-link %}
                        <a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}"
                           class="btn btn-outline-light me-2">Вход</a>
                    {% endblock %}
                    {% block registration-nav-link %}
                        <a href="{% url 'accounts:registration' %}?next={{ request.get_full_path }}"
                           class="btn btn-warning">Регистрация</a>
                    {% endblock %}
                {% endif %}
            </div>
        </div>
    </div>
</header>

{% block content %}
    <div class="container main-container mt-3"></div>
    <div style="display: none" class="container form-container">
    <form>
        <div class="mb-3">
            <label for="text" class="form-label">Quote text</label>
            <textarea class="form-control" id="text" cols="30" rows="10"></textarea>
        </div>
        <div class="mb-3">
            <label for="name" class="form-label">Your name</label>
            <input type="text" class="form-control" id="name">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Your email</label>
            <input type="email" class="form-control" id="email">
        </div>
        <button id="submit" type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
{% endblock %}

<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
</script>
<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>

</body>
</html>