accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserDetailView, UsersListView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('', UsersListView.as_view(), name='users'),
    path('change/', UserChangeView.as_view(), name='profile_change'),
    path('password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<slug:slug>/', UserDetailView.as_view(), name='detail_profile'),
]

hw72/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

api_urlpatterns = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include(api_urlpatterns))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Профиль')
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars', verbose_name='Аватар')
    github_profile = models.URLField(verbose_name='Ссылка на Гитхаб', null=True, blank=True)
    about = models.TextField(max_length=1000, verbose_name='О себе', null=True, blank=True)
    slug = models.SlugField(null=False, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"Профиль: {self.user.username}. {self.id}"

    def get_absolute_url(self):
        return reverse('accounts:detail_profile', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import BaseModelForm

from accounts.models import Profile

User = get_user_model()


class UserFormValidationMixin(BaseModelForm):
    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if not first_name and not last_name:
            raise forms.ValidationError('Хотя бы одно из полей "Имя" или "Фамилия" должны быть заполнены')
        return super().clean()


class MyUserCreationForm(UserCreationForm, UserFormValidationMixin):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")


class UserChangeForm(forms.ModelForm, UserFormValidationMixin):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'slug']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth import login, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from accounts.models import Profile

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = "registration.html"
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('quotes:index')
        return next_url


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    slug_field = 'profile__slug'


class UsersListView(PermissionRequiredMixin, ListView):
    template_name = 'users_list.html'
    model = User
    permission_required = 'accounts.view_profile'

    def get_queryset(self):
        return super().get_queryset().exclude(is_superuser=True)


class UserChangeView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail_profile', kwargs={'slug': self.object.profile.slug})


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('accounts:detail_profile', kwargs={'slug': self.object.profile.slug})

accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Аутентификация{% endblock %}

{% block registration-nav-link %}
    <a href="{% url 'accounts:registration' %}" class="btn btn-warning">Регистрация</a>
{% endblock %}
{% block login-nav-link %}
{% endblock %}

{% block content %}

    <main class="form-signin text-center w-50 ms-auto me-auto mt-5">
        {{ has_error }}
        <h1 class="h3 mb-3 fw-normal">Пожалуйста выполните вход</h1>
        <form method="post">
            {% csrf_token %}
            {% if form.errors %}
                <p class="text-danger">Неверное имя пользователя или пароль!</p>
            {% endif %}
            <div class="form-floating">
                <input type="text" class="form-control" name="username" id="username" placeholder="Имя пользователя">
                <label for="username">Имя пользователя</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" name="password" id="password" placeholder="Пароль">
                <label for="password">Пароль</label>
            </div>
            <br>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
        </form>
    </main>

{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block login-nav-link %}
    <a href="{% url 'accounts:login' %}" class="btn btn-outline-light me-2">Вход</a>
{% endblock %}
{% block registration-nav-link %}
{% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <form method="post">
        {% include "partial/form.html" with button_text="Зарегистрироваться" %}
    </form>
{% endblock %}

accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link px-2 text-white" href="{% url 'accounts:password_change' %}">Смена
    пароля</a></li>
{% endblock %}



{% block content %}
    <h2>Редактирование личных данных</h2>
    <form action="{% url 'accounts:profile_change' %}" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input class="btn btn-primary" type="submit" value="Применить">
    </form>
{% endblock %}

accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Личная страница{% endblock %}

{% block nav %}
    {% if request.user == user_obj %}
        <li class="nav-item"><a class="nav-link px-2 text-white" href="{% url 'accounts:profile_change' %}">Редактировать</a>
        </li>
        <li class="nav-item"><a class="nav-link px-2 text-white" href="{% url 'accounts:password_change' %}">Смена
            пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-7">
                <div class="card p-3 py-4">
                    <div class="text-center">
                        {% if user_obj.profile.avatar %}
                            <img src="{{ user_obj.profile.avatar.url }}" width="200" class="">
                        {% else %}
                            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"
                                 width="200" class="">
                        {% endif %}
                    </div>
                    <div class="text-center mt-3">
                        <span class="bg-secondary p-1 px-4 rounded text-white">{{ user_obj.username }}</span><br>
                        <span>{{ user_obj.email }}</span>
                        {% if user_obj.profile.github_profile %}
                            <p class="mb-0"><a class="link-dark" target="_blank"
                                               href="{{ user_obj.profile.github_profile }}"><i class="bi bi-github"
                                                                                               style="font-size:50px;"></i></a>
                            </p>
                        {% endif %}
                        <h5 class="mb-0">{{ user_obj.first_name }} {{ user_obj.last_name }}</h5>
                        <div class="px-4 mt-1">
                            {% if user_obj.profile.about %}
                                <p class="fonts">{{ user_obj.profile.about }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link px-2 text-white" href="{% url "accounts:profile_change" %}">Редактирование
    профиля</a></li>
{% endblock %}


{% block content %}
    <h2>Смена пароля</h2>
    <form action="{% url 'accounts:password_change' %}" method="post">
        {% include 'partial/form.html' with button_text='Сохранить' %}
    </form>
{% endblock %}

accounts/templates/users_list.html
{% extends 'base.html' %}

{% block title %}Пользователи{% endblock %}

{% block content %}
    <div class="list-group mt-4 w-50 mx-auto">
        <h2>Список пользователей</h2>
        {% for user_obj in user_list %}
            <a href="{% url 'accounts:detail_profile' user_obj.profile.slug %}"
               class="list-group-item list-group-item-action list-group-item-info">{{ user_obj }}</a>
        {% endfor %}
    </div>
{% endblock %}